// DATA RESOURCES
let dataResorce = [
    {
        heading: "Solar Energy",
        bodyText: "Sunlight is a renewable resource, and its most direct use is achieved by capturing the sun’s energy. A variety of solar energy technologies are used to convert the sun’s energy and light into heat: illumination, hot water, electricity and (paradoxically) cooling systems for businesses and industry.Photovoltaic (PV) systems use solar cells to convert sunlight into electricity. Solar hot water systems can be used to heat buildings by circulating water through flat-plate solar collectors. Mirrored dishes that are focused to boil water in a conventional steam generator can produce electricity by concentrating the sun’s heat. Commercial and industrial buildings can also leverage the sun’s energy for larger scale needs such as ventilation, heating and cooling. Finally, thoughtful architectural designs can passively take advantage of the sun as a source of light for heating and cooling.",
        imgUrl: "./images/solar.jpg"
    },
    {
        heading: "Wind Energy",
        bodyText: "Wind can be considered a form of solar energy because the uneven heating and cooling of the atmosphere cause winds (as well as the rotation of the earth and other topographical factors). Wind flow can be captured by wind turbines and converted into electricity. On a smaller scale, windmills are still used today to pump water on farms.Commercial grade wind-powered generating systems are available to meet the renewable energy needs of many organizations.Single-wind turbines can generate electricity to supplement an existing electrical supply. When the wind blows, power generated by the system goes to offset the need for utility supplied electricity.Utility-scale wind farms generate electricity that can be purchased on the wholesale power market, either contractually or through a competitive bid process.",
        imgUrl: "./images/wind.jpg"
    },
    {
        heading: "Hydro Energy",
        bodyText: "Hydropower isn’t a new invention, though the waterwheels once used to operate the gristmills and sawmills of early America are now largely functioning as historic sites and museums.Today, the kinetic energy of flowing rivers is captured in a much different way and converted into hydroelectricity. Probably the most familiar type of hydroelectric power is generated by a system where dams are constructed to store water in a reservoir which, when released, flows through turbines to produce electricity.This is known as “pumped-storage hydropower,” where water is cycled between lower and upper reservoirs to control electricity generation between times of low and peak demand.Another type, called “run-of-river hydropower,” funnels a portion of river flow through a channel and does not require a dam. Hydropower plants can range in size from massive projects such as Hoover Dam to micro-hydroelectric power systems.",
        imgUrl: "./images/hydro.jpg"
    }
];

let $btns = document.querySelectorAll('button');
let $content = document.querySelector(".content");

// EVENT-OBJECT IS ACCESSED 
// AS THE FIRST PARAMETER OF THE EVENT-HANDLER 
function eventHandler(ev){
    
    // fetch the clicked button
    let clickedBtn = ev.target;
    
    // read the text inside the button
    let btnText = clickedBtn.innerText;
    
    // print the text of the clicked button
    //console.log(btnText);
    
    if (btnText === "PAGE 1") {
        $content.innerHTML = `<div><h3>${dataResorce[0].heading}</h3></div>
                              <img src="${dataResorce[0].imgUrl}" alt="placeholder">
                              <p>${dataResorce[0].bodyText}</p>`;
    } else if (btnText === "PAGE 2") {
        $content.innerHTML = `<div><h3>${dataResorce[1].heading}</h3></div>
                              <img src="${dataResorce[1].imgUrl}" alt="placeholder">
                              <p>${dataResorce[1].bodyText}</p>`;
    } else {
        $content.innerHTML = `<div><h3>${dataResorce[2].heading}</h3></div>
                              <img src="${dataResorce[2].imgUrl}" alt="placeholder">
                              <p>${dataResorce[2].bodyText}</p>`;
    }
    
}
//$btns[0].addEventListener("click", clickEvent);
//$btns[1].addEventListener("click", clickEvent);
//$btns[2].addEventListener("click", clickEvent);

for(let i=0; i<$btns.length; i++){
    $btns[i].addEventListener("click", eventHandler);
}